server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: Anurath@123
    driver-class-name: org.postgresql.Driver

  application:
    name=tsnprocessor:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: UTC