server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: Anurath@123
    driver-class-name: org.postgresql.Driver

  application:
    name: wise


google:
  genai:
    api-key: -------------API KEY----------------------------
    model: gemini-2.0-flash # Or your preferred model


nvidia:
  ai:
    api-key: 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
    url: https://integrate.api.nvidia.com/v1/chat/completions

sarvam:
  ai:
    api-key: sk_esg8g8hr_9Am7yWTFr77QsHSknM7biYbS
    sharvamUrl: https://api.sarvam.ai
